server:
  port: 3010

spring:
  application:
    name: ymu-hystrix-dashboard

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.ymu.com:2221/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
